Cleanup test_helper.cpp
microsoft/ebpf-for-windows pull request #1868
Opened 2023-01-12 16:35 UTC by Alan-Jowett

Signed-off-by: Alan Jowett <alanjo@microsoft.com>

Resolves: #661 

## Description

Cleanup test_helper.cpp. Add code analysis annotations and switch to variable names that match coding standards.

## Testing

CI/CD

## Documentation

No.

2023-01-12 17:09 UTC, dv-msft approved these changes

2023-01-12 17:21 UTC, saxena-anurag submitted a review, later dismissed

2023-01-12 17:55 UTC, dthaler commented on tests/end_to_end/test_helper.cpp
> +    _Out_ PDWORD bytes_returned,
PDWORD is still a type that should be replaced.

2023-01-12 17:56 UTC, dthaler requested changes
Please replace PDWORD with unsigned long*

2023-01-12 22:49 UTC, dthaler approved these changes

2023-01-13 17:36 UTC, dv-msft approved these changes

2023-01-13 17:36 UTC, merged