Remove check that prevents fuzzing below minimum size
microsoft/ebpf-for-windows pull request #2849
Opened 2023-09-13 20:43 UTC by Alan-Jowett

## Description

Remove check in fuzzer to permit varying request and reply length.

## Testing

CI/CD

## Documentation

CI/CD

## Installation

No.

2023-09-13 22:38 UTC, dthaler submitted a review, later dismissed

2023-09-16 17:09 UTC, dthaler submitted a review, later dismissed
Ok except for a typo

2023-09-16 17:09 UTC, dthaler commented on libs/execution_context/ebpf_core.c
> +    // Subtract the dat size.
```suggestion
    // Subtract the data size.
```

2023-09-18 16:03 UTC, gtrevi requested changes
We should address default behavior in all `switch` statements.

2023-09-18 16:03 UTC, saxena-anurag submitted a review, later dismissed

2023-09-19 17:57 UTC, dthaler submitted a review, later dismissed
Re-approving after typo fix

2023-09-20 18:43 UTC, dthaler approved these changes

2023-09-20 18:50 UTC, gtrevi approved these changes

2023-09-20 20:35 UTC, merged