Disable /ZI and incremental linking
microsoft/ebpf-for-windows pull request #546
Opened 2021-09-15 20:34 UTC by Alan-Jowett

Disable /ZI and incremental linking

Signed-off-by: Alan Jowett <alanjo@microsoft.com>

2021-09-15 22:48 UTC, shankarseal approved these changes
Thank you!

2021-09-16 14:58 UTC, dthaler requested changes
There are still a number of <LinkIncremental>true</LinkIncremental> across the repo not touched by this PR yet.  For example tools\elfhelper\elfhelper.vcxproj

I'd recommend doing:
```
findstr /s LinkIncremental.true *.vcxproj
```
And verifying that everything shown is intentional.

2021-09-16 14:58 UTC, dthaler commented on tools/dnsflood/dnsflood.vcxproj
>      <LinkIncremental>false</LinkIncremental>
Why is it different for debug vs release?

2021-09-16 14:58 UTC, dthaler commented on tests/libs/common/common_tests.vcxproj
> +      <SupportJustMyCode>false</SupportJustMyCode>
LinkIncremental is still true in lines 79 and 85

2021-09-16 14:58 UTC, dthaler commented on tests/client/ebpf_client.vcxproj
> +    <LinkIncremental>false</LinkIncremental>
What about line 80?

2021-09-16 16:56 UTC, Alan-Jowett commented
Switched everything within this repo to disable incremental linking. We need a PR in the ebpf-verifier repo to disable it there if we need to.

2021-09-16 19:16 UTC, shankarseal approved these changes

2021-09-16 22:39 UTC, dthaler approved these changes

2021-09-16 22:49 UTC, merged