Update Readme.md
microsoft/ebpf-for-windows pull request #833
Opened 2022-03-21 17:28 UTC by dahavey

## Description

Update Readme.md in FAQ section 3 to reflect that the interpreter has been disabled in release builds and now runs only in debug mode.

2022-03-21 17:52 UTC, dahavey commented
Closed PR because it contains too many commits. It should have only 2 commits for the Readme.md file. Will submit a new one.

2022-04-11 00:55 UTC, dahavey commented
I moved the execution context stuff out to issue #926 
This PR contains only the HVCI changes to Readme.md

2022-04-11 15:11 UTC, dthaler requested changes

2022-04-11 16:29 UTC, dthaler commented on README.md
> +Yes. With HVCI enabled eBPF programs can be run natively and interpreted mode, however, the interpreter is disabled in release builds and only supported in debug mode.
```suggestion
Yes. With HVCI enabled, eBPF programs can be run either natively or in interpreted mode.  However, the interpreter is disabled in release builds and is only supported in debug builds.
```

2022-04-11 20:57 UTC, merged